### ISSUE TITLE
App ad

### ISSUE THREAD

**Issue by sswimming** [Apious/AdGuard_Settings#1]
![Screenshot_20201205-091619](https://user-images.githubusercontent.com/74521039/101227263-95dd2280-36da-11eb-8a7a-af36e90c4677.png)
![Screenshot_20201205-091338](https://user-images.githubusercontent.com/74521039/101227266-97a6e600-36da-11eb-92ae-e1ef7f7fa34a.png)
![Screenshot_20201205-091333](https://user-images.githubusercontent.com/74521039/101227269-98d81300-36da-11eb-8a6e-70791c364e6d.png)
![Screenshot_20201205-091327](https://user-images.githubusercontent.com/74521039/101227273-9970a980-36da-11eb-91b7-f4e6dbf0c0c5.png)

캐치딜 앱에서 밑에 설정탭을 제외한 탭들에서 광고가 나오고 키워드 등록을 할 시 검은색이지만 광고창이 생깁니다

@Apious

**Comment by sswimming** [comment]
@Apious 
광고가 저렇게 이미지로 뜰 때가있고 저 칸에 문구로 나올때가 있습니다

앱 : 캐치딜

**Comment by Apious** [comment]
:ok_hand:

**Comment by Apious** [comment]
광고 확인 했네요 차단 돴다해도 흔적이 남거나 우회로 테두리가 남네요 ㅎ
이러면 걍 앱을 mod 로 하는게 났겠네요ㅎ

**Comment by Apious** [comment]
@sswimming 광고 확인 했네요 차단 돴다해도 흔적이 남거나 우회로 테두리가 남네요 ㅎ
이러면 걍 앱을 mod 로 하는게 났겠네요ㅎ

**Comment by sswimming** [comment]
모드로 어떻게하나요??

**Comment by Apious** [comment]
> 모드로 어떻게하나요??

개발자가 아니다보니 mod로 분리는 시킬수 있지만 "키워드 등록-등록" 에서 [광고가 표시됩니다] 후 등록되는 문제가 있네요 -_-ㅎ

그외에는 광고 싹 제거 된 상태이긴 한데.... [ 등록 - 광고 - 키워드 등록 상태 ] 에서 광고를 날렸더니 노출 없이 등록 지연 딜레이가 되네요 ㅋ

등록 - 바로 등록 될지를 보는 중임다 ㅎ

**Comment by Apious** [comment]
> @Apious 
> 광고가 저렇게 이미지로 뜰 때가있고 저 칸에 문구로 나올때가 있습니다
> 
> 앱 : 캐치딜

@sswimming @sswimming 캐치딜 패스 하시고 더 좋은거 추천 "꿀소식" + mod에 광고제거

꿀소식 정보
https://play.google.com/store/apps/details?id=io.oskm.hotdeals

mod
![꿀소식_v2.0.6-NoAds.apk.이미지아님.jpg](https://user-images.githubusercontent.com/75485202/101265657-8b2e9600-378b-11eb-95d9-bd2177d1be5d.jpg)

- 대체되어 닫습니다
