### ISSUE TITLE
쿠팡 광고

### ISSUE THREAD

**Issue by gyujin0429** [Apious/AdGuard_Settings#12]
![Screenshot_20210528-183128](https://user-images.githubusercontent.com/84966084/119964695-70273b00-bfe4-11eb-919a-5565ec294aec.jpg)
![Screenshot_20210528-182701](https://user-images.githubusercontent.com/84966084/119964706-73222b80-bfe4-11eb-850a-fddb231f5b37.jpg)
광고 없애주세요!

**Comment by Apious** [comment]
적용됨 / 오늘 적용함 낼쯤 반영 예정
1. 검색시 키보드 뜨면 하단 광고
2. 마이쿠팡 하단 광고
3. 카테고리 미표시 오류남

제거됨
![Screenshot_20210602-123503](https://user-images.githubusercontent.com/75485202/120421114-aaa42580-c3a0-11eb-8501-a70cc1983f2e.png)
![Screenshot_20210602-123539](https://user-images.githubusercontent.com/75485202/120421136-b263ca00-c3a0-11eb-8c48-f84f7a37203a.png)
![Screenshot_20210602-123617](https://user-images.githubusercontent.com/75485202/120421145-b7c11480-c3a0-11eb-922d-afe8f325037f.png)

**Comment by Apious** [comment]
검색시 키보드 띄울때 하단 광고인데
외부 쿠팡 링크 불러오지 못하는 문제가 앱에서 추가 확인됨으로 제외합니다

||cmapi.coupang.com^
