### ISSUE TITLE
how to solve this issue?

### ISSUE THREAD

**Issue by avernal1819** [Apious/AdGuard_Settings#13]
Issue URL (Anti Adblock Script)
https://1412.rest

Comment
detect ad blocker

메일을 받았는데 다시 광고차단시키려면 어떻게해야하나요

**Comment by Apious** [comment]
Adguard DNS Filter 에서 차단 되었습니다
||pagead2.googlesyndication.com^

Adguard Support team에 문의 하세요
https://github.com/AdguardTeam/AdguardFilters/issues
