### ISSUE TITLE
광고 제거 요청드립니다

### ISSUE THREAD

**Issue by SaintThoma** [Apious/AdGuard_Settings#14]
설정값 정말 귀하게 쓰고 있습니다.
구글 플레이스토어 '성경읽기' 어플 사용중인데, 어플을 켤 때마다 전면광고가 매번 바뀌어가며 나오더라고요. 애드가드 사용중인데  해결이 안 되어 문의드립니다 ㅠ
![Screenshot_20220629-055846](https://user-images.githubusercontent.com/108370265/176287045-e20a1630-ce99-477e-9c95-72c185bc0cb0.jpg)
![Screenshot_20220629-055846](https://user-images.githubusercontent.com/108370265/176287045-e20a1630-ce99-477e-9c95-72c185bc0cb0.jpg)

**Comment by Apious** [comment]
파랑색 앱의 + 모앙의 = 성경읽기(일독) 맞을까요?

1. 앱관리 - 앱 이름 - "https필터링 ON"
2. 앱 정보 - 데이터 - 캐시만 삭제
3. 위와 같이 하면 X만 보이고 우측 상단에 x 누르면 바로 앱 사용이 됩니다

**Comment by Apious** [comment]
파랑색 앱의 + 모앙의 = 성경읽기(일독) 맞을까요?

앱관리 - 앱 이름 - "https필터링 ON"
앱 정보 - 데이터 - 캐시만 삭제
위와 같이 하면 X만 보이고 우측 상단에 x 누르면 바로 앱 사용이 됩니다

**Comment by Apious** [comment]
> 설정값 정말 귀하게 쓰고 있습니다. 구글 플레이스토어 '성경읽기' 어플 사용중인데, 어플을 켤 때마다 전면광고가 매번 바뀌어가며 나오더라고요. 애드가드 사용중인데 해결이 안 되어 문의드립니다 ㅠ ![Screenshot_20220629-055846](https://user-images.githubusercontent.com/108370265/176287045-e20a1630-ce99-477e-9c95-72c185bc0cb0.jpg) ![Screenshot_20220629-055846](https://user-images.githubusercontent.com/108370265/176287045-e20a1630-ce99-477e-9c95-72c185bc0cb0.jpg)

--------------------------------

파랑색 앱의 + 모앙의 = 성경읽기(일독) 맞을까요?

https필터링 켜도 우회되서 광고 노출이 다양하게 변경되서 뜨네요
광고 제거된 앱을 올리니 이걸로 쓰세요

**Comment by Apious** [comment]
@SaintThoma 광고 날린 2.1 버전을 수정해 올리니 참고하세요

링크: https://terabox.com/s/1fmzF8K4LTbly4drjU_4Rsw

**Comment by Apious** [comment]
.

**Comment by SaintThoma** [comment]
정말 감사드립니다!!!
