### ISSUE TITLE
설정 불러오기 오류

### ISSUE THREAD

**Issue by lwc0319** [Apious/AdGuard_Settings#15]
@Apious 
안녕하세요
좋은 자료 공유 감사합니다.
올려주신 설정을 적용하는데 있어 어려움을 느껴 문의를 드립니다.
올려두신 파일은 adguard settings라는 압축파일 하나랑
소스코드라는 이름의 파일 두개로 확인되는데
이 셋중 어느 것을 다운받아서 불러와도 설정을 불러오는 과정에서 오류가 발생했다는 안내가 뜹니다.
압축을 해제해서 json이라는 폴더안의 3가지 파일을 불러와도 같은 상황이구요...
다른 곳에서 다른 분의 json 파일을 다운받아 불러왔을때는 성공적으로 적용이 되었습니다.
제가 어느 부분에서 잘못해서 적용이 안되는 걸까요?
도움 부탁드립니다.

**Comment by Apious** [comment]
네이버 까페 문의로 어제 티스토리에 등록 되었는데요

4.0.xx / 안11
4.0.xxx / 안12 버전으로 되면서 설정이 아예 변경 되었슴다
