### ISSUE TITLE
frontman.tmobiapi.com 삭제 요청

### ISSUE THREAD

**Issue by ssangjin** [Apious/AdGuard_Settings#16]
https://github.com/Apious/Ads_Filter_Contents/blame/1st/Ads_Filter_Contents.txt#L767

frontman.tmobiapi.com 은 광고가 아닌 정상 서비스를 위한 서버입니다.
삭제 요청드립니다.

**Comment by Apious** [comment]
광고 차단 기능 앱을 OFF 하거나
해당 필터를 적용하지 마세요
