### ISSUE TITLE
청와대 국민청원 로그인 오류

### ISSUE THREAD

**Issue by ja0291** [Apious/AdGuard_Settings#2]
안녕하세요! 드디어 가입했네요...ㅠㅠ백단향입니다. 
깃허브에서 계속 가입오류가 떴던 이유가 애드가드 때문이였어요ㅠㅠ끄고 하니까 잘 되더라구요.
그리고 댓글에서 문의드렸던 필터리스트(?)에 대한 궁금증도 해결했습니다. 
쉽게 말해 필터리스트가 있는 링크를 걸어놓고 Apious님이 해당 링크에서 필터를 추가하면 그 링크를 등록해놓은 사용자는 자동업데이트가 되는 획기적인 방법이였네요. 
제가 이해가 부족해 많이 답답하셨을텐데 죄송합니다ㅜ

제보드릴 오류는
https://www1.president.go.kr/petitions/594131
청와대 국민청원 페이지에서 청원에 동의하기를 하려고 하면 소셜로그인창으로 넘어가게 되는데요. 
로그인을 하면 
http://www.president.go.kr
계속 기본 페이지로 넘어가고, 다시 청원 동의하기를 하려고 찾아서 들어가면 로그인이 안되어있고...
무한반복입니다. 
이것도 혹시나 싶어 애드가드를 끄고 하니까 로그인되고 해당 청원 페이지에서 바로 동의할 수 있게 넘어가더라구요. 확인 부탁드릴게요^^

그리고 처음 말씀드렸다시피 애드가드를 키고 있으면 깃허브 가입단계에서 계속 오류나면서 막히는 현상이 있습니다. 
저야 이제 가입완료되서 상관없지만 혹시 싶어 같이 제보드려요^^

**Comment by Apious** [comment]
> 안녕하세요! 드디어 가입했네요...ㅠㅠ백단향입니다.
> 깃허브에서 계속 가입오류가 떴던 이유가 애드가드 때문이였어요ㅠㅠ끄고 하니까 잘 되더라구요.
> 그리고 댓글에서 문의드렸던 필터리스트(?)에 대한 궁금증도 해결했습니다.
> 쉽게 말해 필터리스트가 있는 링크를 걸어놓고 Apious님이 해당 링크에서 필터를 추가하면 그 링크를 등록해놓은 사용자는 자동업데이트가 되는 획기적인 방법이였네요.
> 제가 이해가 부족해 많이 답답하셨을텐데 죄송합니다ㅜ
> 
> 제보드릴 오류는
> https://www1.president.go.kr/petitions/594131
> 청와대 국민청원 페이지에서 청원에 동의하기를 하려고 하면 소셜로그인창으로 넘어가게 되는데요.
> 로그인을 하면
> http://www.president.go.kr
> 계속 기본 페이지로 넘어가고, 다시 청원 동의하기를 하려고 찾아서 들어가면 로그인이 안되어있고...
> 무한반복입니다.
> 이것도 혹시나 싶어 애드가드를 끄고 하니까 로그인되고 해당 청원 페이지에서 바로 동의할 수 있게 넘어가더라구요. 확인 부탁드릴게요^^
> 
> 그리고 처음 말씀드렸다시피 애드가드를 키고 있으면 깃허브 가입단계에서 계속 오류나면서 막히는 현상이 있습니다.
> 저야 이제 가입완료되서 상관없지만 혹시 싶어 같이 제보드려요^^

답변이 늦었네요
바로 예외 적용 되었슴다
