### ISSUE TITLE
네이버 오류신고

### ISSUE THREAD

**Issue by ja0291** [Apious/AdGuard_Settings#3]
https://m.naver.com/aside/
일반 브라우저에서 페이지 진입시
애드가드 해제시 원래 하단처럼 나오는 게 정상인데
![Screenshot_20201208-040251_Samsung Internet](https://user-images.githubusercontent.com/75616113/101393487-85ab8a00-390a-11eb-84b0-8c0dc5019df1.jpg)
애드가드를 킨 상태에서 진입하면 하단처럼 아이디창쪽이 비어서 나오는 오류가 발견되었습니다
![Screenshot_20201208-040237_Samsung Internet](https://user-images.githubusercontent.com/75616113/101393594-ad9aed80-390a-11eb-8696-cc116f50dd2c.jpg)

**Comment by Apious** [comment]
> https://m.naver.com/aside/
> 일반 브라우저에서 페이지 진입시
> 애드가드 해제시 원래 하단처럼 나오는 게 정상인데
> ![Screenshot_20201208-040251_Samsung Internet](https://user-images.githubusercontent.com/75616113/101393487-85ab8a00-390a-11eb-84b0-8c0dc5019df1.jpg)
> 애드가드를 킨 상태에서 진입하면 하단처럼 아이디창쪽이 비어서 나오는 오류가 발견되었습니다
> ![Screenshot_20201208-040237_Samsung Internet](https://user-images.githubusercontent.com/75616113/101393594-ad9aed80-390a-11eb-8696-cc116f50dd2c.jpg)

네 알고 있는 문제인데 전바적인걸 변경하느라 ㅎ
오늘 싹다 수정 되었슴다
