### ISSUE TITLE
네이버앱 오류 제보

### ISSUE THREAD

**Issue by ja0291** [Apious/AdGuard_Settings#4]
![Screenshot_20201211-044630_NAVER](https://user-images.githubusercontent.com/75616113/101826169-f43e5100-3b71-11eb-96ec-3567f432e0e5.jpg)
네이버앱 메인에서 엑박광고가 뜨는 오류
![Screenshot_20201211-044658_NAVER](https://user-images.githubusercontent.com/75616113/101826209-03bd9a00-3b72-11eb-904d-0d36ba98170c.jpg)
네이버앱에서 검색을 하면 이미지가 다 깨져서 나오는 오류가 발견되었습니다. 
어느 검색어든 마찬가지지만, url첨부를 하자면
https://m.search.naver.com/search.naver?sm=mtb_hty.top&where=m&oquery=3s&tqi=U96aKdp0JWVsskoTlaVssssstNR-416326&query=%EC%95%A0%ED%94%8C

그리고 네이버앱에서 검색을 통한 블로그 진입이 되지 않는 문제도 발견되었습니다. 
![Screenshot_20201211-053459_NAVER](https://user-images.githubusercontent.com/75616113/101826649-a37b2800-3b72-11eb-9548-18c45b22ce21.jpg)

url주소는
https://m.post.naver.com/viewer/postView.nhn?volumeNo=29634578&memberNo=724&vType=VERTICAL

입니다. 
감사합니다.

**Comment by Apious** [comment]
수정 했슴다

이전 차단 후 예외 적용 했으나 후 확인하니 https 라서
[ ||ssl.pstatic.net^ ] 만 먹고 [ ||ssl.pstatic.net^$domain=domain.com ] 이건 전혀 안먹네여ㅎ
걍 해제 하는게 답인듯;;

차단하면 싹다 문의 처럼 보이예외 적용 했으나 후 확인하니 https 라서
[ ||ssl.pstatic.net^ ] 만 먹고 [ ||ssl.pstatic.net^$domain=domain.com ] 이건 전혀 안먹네여ㅎ
걍 해제 하는게 답인듯;;

차단하면 싹다 문의 처럼 보이네요
완료 > 닫슴돠

**Comment by ja0291** [comment]
'걍 해제하는게 답인듯' 이라는게 네이버앱을 adguard보호 해제하는게 낫다는 말씀이신거죠?!

**Comment by Apious** [comment]
@ja0291 다 되게 반영 했어요
- 광고 "명령문"을 해제 했어요~
