### ISSUE TITLE
카카오톡 오류제보

### ISSUE THREAD

**Issue by ja0291** [Apious/AdGuard_Settings#5]
![Screenshot_20201211-065927_KakaoTalk](https://user-images.githubusercontent.com/75616113/101835205-c57aa780-3b7e-11eb-87ed-a64a33e3f471.jpg)

카카오톡을 통해 전송받은 링크를 카카오톡을 통해 접속하면

![Screenshot_20201211-065622_KakaoTalk](https://user-images.githubusercontent.com/75616113/101835235-d0cdd300-3b7e-11eb-8aeb-daff4de07564.jpg)

해당 스샷처럼 화면이 깨져서 나오는 증상이 발생합니다. 
참고로 일반 브라우저, 네이버앱 애드가드필터 비활성화된 상태에서 이렇게 나오네요. 
정작 일반 브라우저, 네이버앱 활성화된 상태에서 해당 링크 붙여넣기하여 접속하면 화면이 깨져서 나오지 않습니다. 
카카오톡에 무언가 문제가 있는 것 같습니다.

**Comment by Apious** [comment]
네 수정 했슴다
11~12일 사이 수정을 반영했는데 필터 수정해도 실제 반영 주기가 48시간 지정되서
이번 설정값에 24시간, wifi아녀도 업뎃 되게 적용 했어요

- 이미지 서버 ssl.pstatic.net 카톡앱에 예외 적용
#4
