### ISSUE TITLE
광고 제거 요청드려요

### ISSUE THREAD

**Issue by YJ-A** [Apious/AdGuard_Settings#6]
![Screenshot_20210208-094307_EarFlip](https://user-images.githubusercontent.com/78709424/107164363-13325580-69f2-11eb-90f9-922d551540e5.jpg)

요거 제거 요청드려도 될까요?
하단에 광고가 나옵니다. 네트워크 모드에서만 나오는것 같네요.
어플 이름은 이어플립입니다.
매번 감사드립니다.

**Comment by Apious** [comment]
네 확인중...

**Comment by Apious** [comment]
![Screenshot_20210215-133314](https://user-images.githubusercontent.com/75485202/107905763-d4247700-6f92-11eb-86d7-03df8a71ded1.png)
차단 적용 됨

우회 dns 차단
||www.googletagservices.com^
||fonts.googleapis.com^

**Comment by YJ-A** [comment]
감사합니다!!!
